### ISSUE TITLE
BUG: when runing "npm run build"

### ISSUE THREAD

**Issue by darbi-a** [webwizarts/chatgpt-exporter#2]
~/chatgpt-exporter$ npm run build

> chat-gpt-export@1.0.0 build
> npm run clean && webpack

> chat-gpt-export@1.0.0 clean
> rm -rf dist

[webpack-cli] TypeError: manifestContent.replaceAll is not a function
    at /home/xxxxx/chatgpt-exporter/webpack.config.js:68:43
    at Hook.eval [as callAsync] (eval at create (/home/xxxxx/chatgpt-exporter/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/xxxxx/chatgpt-exporter/node_modules/tapable/lib/Hook.js:18:14)
    at /home/xxxxx/chatgpt-exporter/node_modules/webpack/lib/Compiler.js:498:23
    at Compiler.emitRecords (/home/xxxxx/chatgpt-exporter/node_modules/webpack/lib/Compiler.js:919:5)
    at /home/xxxxx/chatgpt-exporter/node_modules/webpack/lib/Compiler.js:490:11
    at /home/xxxxx/chatgpt-exporter/node_modules/webpack/lib/Compiler.js:885:14
    at Hook.eval [as callAsync] (eval at create (/home/xxxxx/chatgpt-exporter/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/xxxxx/chatgpt-exporter/node_modules/tapable/lib/Hook.js:18:14)
    at /home/xxxxx/chatgpt-exporter/node_modules/webpack/lib/Compiler.js:882:27

**Comment by oikantik** [comment]
Hi! You might need to make sure you are using nodejs 15.0.0 or higher. LMK if that helps, thanks!

**Comment by darbi-a** [comment]
> Hi! You might need to make sure you are using nodejs 15.0.0 or higher. LMK if that helps, thanks!

You are right, thank you.
It works as intended with v18.15.0
